/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stoktakip;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author veranur
 */
public class frm_login extends javax.swing.JFrame {

    /**
     * Creates new form giriş
     */
    baglanti b = new baglanti();
    personel p;

    public frm_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordYonetici = new javax.swing.JPasswordField();
        kullaniciAdYonetici = new javax.swing.JTextField();
        loginYonetici = new javax.swing.JButton();
        iptalYonetici = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idPersonel = new javax.swing.JTextField();
        kullaniciAdPersonel = new javax.swing.JTextField();
        passwordPersonel = new javax.swing.JPasswordField();
        loginPersonel = new javax.swing.JButton();
        iptalPersonel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Ekranı");

        jLabel2.setText("Kullanıcı Adı:");

        jLabel3.setText("Şifre:");

        loginYonetici.setText("Giriş");
        loginYonetici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginYoneticiActionPerformed(evt);
            }
        });

        iptalYonetici.setText("İptal");
        iptalYonetici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalYoneticiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdYonetici, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(passwordYonetici))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(iptalYonetici, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginYonetici, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(kullaniciAdYonetici))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordYonetici, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginYonetici, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(iptalYonetici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Yönetici Girişi", jPanel2);

        jLabel4.setText("Personel Id: ");

        jLabel5.setText("Kullanıcı Ad:");

        jLabel6.setText("Şifre:");

        loginPersonel.setText("Giriş");
        loginPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPersonelActionPerformed(evt);
            }
        });

        iptalPersonel.setText("İptal");
        iptalPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalPersonelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idPersonel)
                    .addComponent(passwordPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(kullaniciAdPersonel))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(iptalPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullaniciAdPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(iptalPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personel Girişi", jPanel1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Stok Takip Sistemine Hoşgeldiniz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bu metot, "Yönetici Girişi" butonuna tıklandığında çalışır ve yönetici
     * giriş bilgilerini doğrular. Kullanıcı adı ve şifre alanlarının boş olup
     * olmadığını, belirli bir formatta olup olmadığını ve doğru giriş
     * bilgileriyle eşleşip eşleşmediğini kontrol eder. Eğer bilgiler doğruysa,
     * yönetici frame açar, aksi takdirde hata mesajı gösterir.
     */
    private void loginYoneticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginYoneticiActionPerformed
        yönetici yönetici = new yönetici(1, "yönetici1", "12345");
        char[] pass = passwordYonetici.getPassword();
        String password = String.valueOf(pass);
        String kullaniciAd = kullaniciAdYonetici.getText();
        String kullaniciAdRegex = "^[a-zA-Z0-9ğüşöçıIİĞÜŞÖÇ]{3,20}$";
        String sifreRegex = "^[0-9]{5,20}$";

        try {
            if (kullaniciAd.isEmpty() || password.isEmpty()) {
                throw new Exception("Giriş kısımları boş bırakılamaz.");
            }
            if (!kullaniciAd.matches(kullaniciAdRegex)) {
                throw new Exception("Geçersiz kullanıcı adı. Kullanıcı adı 3-20 karakter uzunluğunda olmalı ve sadece harfler ve rakamlardan oluşmalıdır.");
            }
            if (!password.matches(sifreRegex)) {
                throw new Exception("Geçersiz şifre. Şifre 5-20 karakter uzunluğunda olmalı ve sadece sayılardan oluşmalıdır.");
            }

            if (kullaniciAd.equals(yönetici.getKullaniciad()) && password.equals(yönetici.getPassword())) {
                new frm_yönetici().setVisible(true);
                this.dispose();
            } else {
                throw new Exception("Yanlış Kullanıcı adı veya Şİfre tekrar deneyiniz.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_loginYoneticiActionPerformed
    /**
     * Bu metot, "Personel Girişi" butonuna tıklandığında çalışır ve personel
     * giriş bilgilerini doğrular. Kullanıcı adı, şifre ve ID alanlarının boş
     * olup olmadığını, belirli bir formatta olup olmadığını ve veritabanında
     * eşleşen bir kayıt olup olmadığını kontrol eder. Eğer bilgiler doğruysa,
     * stok frame açar, aksi takdirde hata mesajı gösterir.
     */
    private void loginPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPersonelActionPerformed
        ResultSet rs;
        char[] pass = passwordPersonel.getPassword();
        String password = String.valueOf(pass);
        String kullaniciAd = kullaniciAdPersonel.getText();
        String kullanici = "";
        String şifre = "";
        String sorgu = "select * from stok_sistemi.personel where id=" + idPersonel.getText();
        String id = "^[0-9]{1,5}$";
        String kullaniciAdRegex = "^[a-zA-Z0-9ğüşöçıIİĞÜŞÖÇ]{3,20}$";
        String sifreRegex = "^[0-9]{1,8}$";

        try {
            rs = b.executeQuery(sorgu);
            while (rs.next()) {

                kullanici = rs.getString("kullaniciAd");
                şifre = rs.getString("sifre");

            }
            if (kullaniciAd.isEmpty() || password.isEmpty() || idPersonel.getText().isEmpty()) {
                throw new Exception("Giriş kısımları boş bırakılamaz.");
            }
            if (!kullaniciAd.matches(kullaniciAdRegex)) {
                throw new Exception("Geçersiz kullanıcı adı. Kullanıcı adı 3-20 karakter uzunluğunda olmalı ve sadece harfler ve rakamlardan oluşmalıdır.");
            }
            if (!password.matches(sifreRegex)) {
                throw new Exception("Geçersiz şifre. Şifre 1-8 karakter uzunluğunda olmalı ve sadece sayılardan oluşmalıdır.");
            }
            if (!idPersonel.getText().matches(id)) {
                throw new Exception("Geçersiz id. Id 1-5 karakter uzunluğunda olmalı ve sadece sayılardan oluşmalıdır.");
            }

            if (kullaniciAd.equals(kullanici) && password.equals(şifre)) {

                p = new personel(Integer.parseInt(idPersonel.getText()), kullaniciAd, password);
                p.personelList.add(p);
                new frm_stok(p).setVisible(true);
                this.dispose();
            } else {
                throw new Exception("Yanlış Kullanıcı adı veya Şİfre tekrar deneyiniz.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_loginPersonelActionPerformed

    private void iptalYoneticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalYoneticiActionPerformed
        this.dispose();
    }//GEN-LAST:event_iptalYoneticiActionPerformed

    private void iptalPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalPersonelActionPerformed
        this.dispose();
    }//GEN-LAST:event_iptalPersonelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idPersonel;
    private javax.swing.JButton iptalPersonel;
    private javax.swing.JButton iptalYonetici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kullaniciAdPersonel;
    private javax.swing.JTextField kullaniciAdYonetici;
    private javax.swing.JButton loginPersonel;
    private javax.swing.JButton loginYonetici;
    private javax.swing.JPasswordField passwordPersonel;
    private javax.swing.JPasswordField passwordYonetici;
    // End of variables declaration//GEN-END:variables
}
