/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stoktakip;

/**
 *
 * @author veranur
 */
public class frm_yönetici extends javax.swing.JFrame {

    /**
     * Creates new form yöneticiEkran
     */
    frm_int_bildirim bYönetici;

    public frm_yönetici() {
        initComponents();
        bYönetici = new frm_int_bildirim();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        bildirim = new javax.swing.JButton();
        aylıkSatis = new javax.swing.JButton();
        personelEkle = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        listeleIslem = new javax.swing.JButton();
        stokGirisButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetici Ekranı");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bildirim.setText("Bildirimler");
        bildirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bildirimActionPerformed(evt);
            }
        });
        getContentPane().add(bildirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, 30));

        aylıkSatis.setText("Aylık Satış ");
        aylıkSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aylıkSatisActionPerformed(evt);
            }
        });
        getContentPane().add(aylıkSatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 140, 30));

        personelEkle.setText("Personel İşlemleri");
        personelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelEkleActionPerformed(evt);
            }
        });
        getContentPane().add(personelEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 140, 30));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));
        jDesktopPane1.setForeground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 540));

        listeleIslem.setText("Listeleme İşlemleri");
        listeleIslem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeleIslemActionPerformed(evt);
            }
        });
        getContentPane().add(listeleIslem, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 140, 30));

        stokGirisButton.setText("Stok Girişleri");
        stokGirisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokGirisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stokGirisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 140, 30));

        jButton1.setText("Giriş Ekranı");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 110, 40));

        jMenu2.setText("Ekleme Yap");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bildirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bildirimActionPerformed
        jDesktopPane1.add(bYönetici);
        bYönetici.setVisible(true);
    }//GEN-LAST:event_bildirimActionPerformed

    private void personelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelEkleActionPerformed
        frm_int_personelEkle pEkle = new frm_int_personelEkle();
        jDesktopPane1.add(pEkle).setVisible(true);
    }//GEN-LAST:event_personelEkleActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        new frm_int_EklemeMarkaKategori().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void listeleIslemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeleIslemActionPerformed
        frm_int_listeleme ls = new frm_int_listeleme();
        jDesktopPane1.add(ls);
        ls.setVisible(true);
    }//GEN-LAST:event_listeleIslemActionPerformed

    private void stokGirisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokGirisButtonActionPerformed
        frm_int_stokGiris sg = new frm_int_stokGiris();
        jDesktopPane1.add(sg);
        sg.setVisible(true);
    }//GEN-LAST:event_stokGirisButtonActionPerformed

    private void aylıkSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aylıkSatisActionPerformed
        frm_int_aylıkSatis as = new frm_int_aylıkSatis();
        jDesktopPane1.add(as);
        as.setVisible(true);
    }//GEN-LAST:event_aylıkSatisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new frm_login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_yönetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_yönetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_yönetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_yönetici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_yönetici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aylıkSatis;
    private javax.swing.JButton bildirim;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton listeleIslem;
    private javax.swing.JButton personelEkle;
    private javax.swing.JButton stokGirisButton;
    // End of variables declaration//GEN-END:variables
}
