/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package stoktakip;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.*;

/**
 *
 * @author veranur
 */
public class frm_int_aylıkSatis extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_int_aylıkSatis
     */
    baglanti b = new baglanti();
    DefaultTableModel model;

    /**
     * Aylık satış verilerini tabloya yükler. // Ayın başından bugüne kadar olan
     * satışları ürün ID'si bazında toplar ve JTable'da gösterir.
     */

    public frm_int_aylıkSatis() {
        initComponents();
        model = new DefaultTableModel(new String[]{"Urun ID", "Toplam Adet"}, 0);

        LocalDate today = LocalDate.now();
        LocalDate firstDayOfMonth = today.withDayOfMonth(1);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        try {

            String query = "SELECT urunId, SUM(adet) AS toplamAdet "
                    + "FROM satislar "
                    + "WHERE tarih >= ? AND tarih <= ? "
                    + "GROUP BY urunId";

            PreparedStatement ps = b.preparedStatement(query);
            ps.setString(1, firstDayOfMonth.format(formatter));
            ps.setString(2, today.format(formatter));

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int urunID = rs.getInt("urunId");
                int toplamAdet = rs.getInt("toplamAdet");
                model.addRow(new Object[]{urunID, toplamAdet});
            }

            jTable1.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Aylık Satış");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ürün Id:", "Toplam Adet"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
