/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stoktakip;

import java.sql.*;
import java.time.*;
import javax.swing.*;

/**
 *
 * @author veranur
 */
public class frm_urunEkle extends javax.swing.JFrame {

    /**
     * Creates
     */
    baglanti b = new baglanti();

    public frm_urunEkle() {
        initComponents();
        b.comboBox("select * from stok_sistemi.kategori ", "kategoriAd", kategoriCombo);
        b.comboBox("select * from stok_sistemi.marka ", "markaAd", markaCombo);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kaydetButton = new javax.swing.JButton();
        iptalButton = new javax.swing.JButton();
        adText = new javax.swing.JTextField();
        kategoriCombo = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        fiyatText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        markaCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ürün Ekleme Ekranı");

        jLabel1.setText("Adı:");

        jLabel2.setText("Kategori Seç:");

        jLabel3.setText("Tarih Seç:");

        jLabel4.setText("Fiyat Gir:");

        kaydetButton.setText("Kaydet");
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        iptalButton.setText("iptal");
        iptalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Marka Seç:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adText)
                    .addComponent(kategoriCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(markaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(fiyatText))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iptalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(adText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(kategoriCombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(markaCombo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(fiyatText))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iptalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Bu metot, "Kaydet" butonuna tıklandığında çalışır ve yeni bir ürün kaydı
     * ekler. Kullanıcı tarafından girilen bilgileri alır, geçerliliklerini
     * kontrol eder ve geçerliyse veritabanına yeni bir ürün kaydı ekler.
     * Herhangi bir hata durumunda kullanıcıya hata mesajı gösterir.
     */

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
        LocalDate today = LocalDate.now();
        PreparedStatement s;
        String ad = adText.getText();
        String marka = markaCombo.getSelectedItem().toString();
        String kategori = kategoriCombo.getSelectedItem().toString();
        String date = null;
        if (jDateChooser1.getDate() != null) {
            date = String.valueOf(new java.sql.Date(jDateChooser1.getDate().getTime()));
        }

        String adRegex = "^[a-zA-ZğüşöçıİĞÜŞÖÇI ]{1,50}$";
        String fiyatRegex = "^[0-9]{1,10}$";
        try {
            if (!adText.getText().matches(adRegex)) {
                throw new Exception("Geçersiz Ad girişi. Ad sadece harflerden oluşabilir");
            }
            if (!fiyatText.getText().matches(fiyatRegex)) {
                throw new Exception("Geçersiz fiyat girişi. Fiyat sadece rakamlardan oluşabilir");
            }
            if (ad.isEmpty() || marka.isEmpty() || kategori.isEmpty() || fiyatText.getText().isEmpty()) {
                throw new Exception("Giriş kısımları boş bırakılamaz.");
            }
            if (date == null) {
                throw new Exception("Tarih kısmı boş bırakılamaz. Lütfen tarih seçiniz.");
            }
            if (jDateChooser1.getDate() != null) {
                LocalDate selectedLocalDate = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                if (selectedLocalDate.isAfter(today)) {
                    throw new Exception("İleri bir tarih seçemezsiniz. Lütfen bugünün veya geçmiş bir tarihi seçin.");

                }
            }
            int fiyat = Integer.parseInt(fiyatText.getText());
            String q = "INSERT INTO stok_sistemi.ürünler (ad,marka,kategori,fiyat,tarih) VALUES (?,?,?,?,?)";
            s = b.preparedStatement(q);
            s.setString(1, ad);
            s.setString(2, marka);
            s.setString(3, kategori);
            s.setInt(4, fiyat);
            s.setString(5, date);

            int update = s.executeUpdate();

            if (update > 0) {
                JOptionPane.showMessageDialog(this, "Ürün Başarıyla Eklendi");
            } else {
                JOptionPane.showMessageDialog(this, "Ürün Eklenirken Bir Sorun Oluştu", "sonuc", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        adText.setText("");
        fiyatText.setText("");
        kategoriCombo.setSelectedIndex(0);
        markaCombo.setSelectedIndex(0);
        jDateChooser1.setDate(null);

    }//GEN-LAST:event_kaydetButtonActionPerformed

    private void iptalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_iptalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_urunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_urunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_urunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_urunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_urunEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adText;
    private javax.swing.JTextField fiyatText;
    private javax.swing.JButton iptalButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> kategoriCombo;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JComboBox<String> markaCombo;
    // End of variables declaration//GEN-END:variables
}
